<a href="https://colab.research.google.com/github/MangoHaha/SentimentAnalysis/blob/investigate_new_Arch/SentimentAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## General information

In this kernel I'll work with data from Movie Review Sentiment Analysis Playground Competition.

This dataset is interesting for NLP researching. Sentences from original dataset were split in separate phrases and each of them has a sentiment label. Also a lot of phrases are really short which makes classifying them quite challenging. Let's try!

In [8]:
!pip install lightgbm wordcloud


    100% |████████████████████████████████| 1.1MB 14.5MB/s 
    100% |████████████████████████████████| 368kB 27.3MB/s 


In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

from nltk.tokenize import TweetTokenizer
import datetime
import lightgbm as lgb
from scipy import stats
from scipy.sparse import hstack, csr_matrix
from sklearn.model_selection import train_test_split, cross_val_score
from wordcloud import WordCloud
from collections import Counter
from nltk.corpus import stopwords
from nltk.util import ngrams
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.multiclass import OneVsRestClassifier
pd.set_option('max_colwidth',400)
from google.colab import drive
import nltk
nltk.download('stopwords')
from google.colab import files


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [10]:
from google.colab import drive
drive.mount('/content/drive')


Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
!ls "/content/drive/My Drive/DeepLearning"

crawl-300d-2M.vec	   sampleSubmission.csv  train.tsv
glove.twitter.27B.25d.txt  test.tsv


In [0]:

train = pd.read_csv('/content/drive/My Drive/DeepLearning/train.tsv', sep="\t")
test = pd.read_csv('/content/drive/My Drive/DeepLearning/test.tsv', sep="\t")
sub = pd.read_csv('/content/drive/My Drive/DeepLearning/sampleSubmission.csv', sep=",")

In [16]:
train.head(10)

PhraseId  SentenceId  \
0         1           1   
1         2           1   
2         3           1   
3         4           1   
4         5           1   
5         6           1   
6         7           1   
7         8           1   
8         9           1   
9        10           1   

                                                                                                                                                                                         Phrase  \
0  A series of escapades demonstrating the adage that what is good for the goose is also good for the gander , some of which occasionally amuses but none of which amounts to much of a story .   
1                                                                                                                 A series of escapades demonstrating the adage that what is good for the goose   
2                                                                                                                                                                                      A series   
3                                                                                                                                                                                             A   
4                                                                                                                                                                                        series   
5                                                                                                                          of escapades demonstrating the adage that what is good for the goose   
6                                                                                                                                                                                            of   
7                                                                                                                             escapades demonstrating the adage that what is good for the goose   
8                                                                                                                                                                                     escapades   
9                                                                                                                                       demonstrating the adage that what is good for the goose   

   Sentiment  
0          1  
1          2  
2          2  
3          2  
4          2  
5          2  
6          2  
7          2  
8          2  
9          2

In [17]:
train.loc[train.SentenceId == 2]

PhraseId  SentenceId  \
63        64           2   
64        65           2   
65        66           2   
66        67           2   
67        68           2   
68        69           2   
69        70           2   
70        71           2   
71        72           2   
72        73           2   
73        74           2   
74        75           2   
75        76           2   
76        77           2   
77        78           2   
78        79           2   
79        80           2   
80        81           2   

                                                                        Phrase  \
63  This quiet , introspective and entertaining independent is worth seeking .   
64                     This quiet , introspective and entertaining independent   
65                                                                        This   
66                          quiet , introspective and entertaining independent   
67                                      quiet , introspective and entertaining   
68                                                                       quiet   
69                                            , introspective and entertaining   
70                                              introspective and entertaining   
71                                                           introspective and   
72                                                               introspective   
73                                                                         and   
74                                                                entertaining   
75                                                                 independent   
76                                                          is worth seeking .   
77                                                            is worth seeking   
78                                                                    is worth   
79                                                                       worth   
80                                                                     seeking   

    Sentiment  
63          4  
64          3  
65          2  
66          4  
67          3  
68          2  
69          3  
70          3  
71          3  
72          2  
73          2  
74          4  
75          2  
76          3  
77          4  
78          2  
79          2  
80          2

In [0]:
print('Average count of phrases per sentence in train is {0:.0f}.'.format(train.groupby('SentenceId')['Phrase'].count().mean()))
print('Average count of phrases per sentence in test is {0:.0f}.'.format(test.groupby('SentenceId')['Phrase'].count().mean()))

In [0]:
print('Number of phrases in train: {}. Number of sentences in train: {}.'.format(train.shape[0], len(train.SentenceId.unique())))
print('Number of phrases in test: {}. Number of sentences in test: {}.'.format(test.shape[0], len(test.SentenceId.unique())))

In [0]:
print('Average word length of phrases in train is {0:.0f}.'.format(np.mean(train['Phrase'].apply(lambda x: len(x.split())))))
print('Average word length of phrases in test is {0:.0f}.'.format(np.mean(test['Phrase'].apply(lambda x: len(x.split())))))

We can see than sentences were split in 18-20 phrases at average and a lot of phrases contain each other. Sometimes one word or even one punctuation mark influences the sentiment

Let's see for example most common trigrams for positive phrases

In [0]:
text = ' '.join(train.loc[train.Sentiment == 4, 'Phrase'].values)
text_trigrams = [i for i in ngrams(text.split(), 3)]

In [0]:
Counter(text_trigrams).most_common(30)

In [19]:
text = ' '.join(train.loc[train.Sentiment == 4, 'Phrase'].values)
text = [i for i in text.split() if i not in stopwords.words('english')]
text_trigrams = [i for i in ngrams(text, 3)]
Counter(text_trigrams).most_common(30)

[((',', 'funny', ','), 33),
 (('one', 'year', "'s"), 28),
 (('year', "'s", 'best'), 26),
 (('movies', 'ever', 'made'), 19),
 ((',', 'solid', 'cast'), 19),
 (('solid', 'cast', ','), 18),
 (("'ve", 'ever', 'seen'), 16),
 (('.', 'It', "'s"), 16),
 ((',', 'making', 'one'), 15),
 (('best', 'films', 'year'), 15),
 ((',', 'touching', ','), 15),
 (('exquisite', 'acting', ','), 15),
 (('acting', ',', 'inventive'), 14),
 ((',', 'inventive', 'screenplay'), 14),
 (('jaw-dropping', 'action', 'sequences'), 14),
 (('good', 'acting', ','), 14),
 (("'s", 'best', 'films'), 14),
 (('I', "'ve", 'seen'), 14),
 (('funny', ',', 'even'), 14),
 (('best', 'war', 'movies'), 13),
 (('purely', 'enjoyable', 'satisfying'), 13),
 (('funny', ',', 'touching'), 13),
 ((',', 'smart', ','), 13),
 (('inventive', 'screenplay', ','), 13),
 (('funniest', 'jokes', 'movie'), 13),
 (('action', 'sequences', ','), 13),
 (('sequences', ',', 'striking'), 13),
 ((',', 'striking', 'villains'), 13),
 (('exquisite', 'motion', 'picture')

The results show the main problem with this dataset: there are to many common words due to sentenced splitted in phrases. As a result stopwords shouldn't be removed from text.

### Thoughts on feature processing and engineering

So, we have only phrases as data. And a phrase can contain a single word. And one punctuation mark can cause phrase to receive a different sentiment. Also assigned sentiments can be strange. This means several things:
- using stopwords can be a bad idea, especially when phrases contain one single stopword;
- puntuation could be important, so it should be used;
- ngrams are necessary to get the most info from data;
- using features like word count or sentence length won't be useful;

In [0]:
tokenizer = TweetTokenizer()

In [0]:
vectorizer = TfidfVectorizer(ngram_range=(1, 2), tokenizer=tokenizer.tokenize)
full_text = list(train['Phrase'].values) + list(test['Phrase'].values)
vectorizer.fit(full_text)
train_vectorized = vectorizer.transform(train['Phrase'])
test_vectorized = vectorizer.transform(test['Phrase'])

In [22]:
vocab_size = len(vectorizer.get_feature_names()) + 1
print(vocab_size)

128270


In [0]:
y = train['Sentiment']

In [0]:
logreg = LogisticRegression()
ovr = OneVsRestClassifier(logreg)

In [0]:
%%time
ovr.fit(train_vectorized, y)

In [0]:
scores = cross_val_score(ovr, train_vectorized, y, scoring='accuracy', n_jobs=-1, cv=3)
print('Cross-validation mean accuracy {0:.2f}%, std {1:.2f}.'.format(np.mean(scores) * 100, np.std(scores) * 100))

In [0]:
%%time
svc = LinearSVC(dual=False)
scores = cross_val_score(svc, train_vectorized, y, scoring='accuracy', n_jobs=-1, cv=3)
print('Cross-validation mean accuracy {0:.2f}%, std {1:.2f}.'.format(np.mean(scores) * 100, np.std(scores) * 100))

In [0]:
ovr.fit(train_vectorized, y);
svc.fit(train_vectorized, y);

## Deep learning
And now let's try DL. DL should work better for text classification with multiple layers. I use an architecture similar to those which were used in toxic competition.

In [24]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.layers import Dense, Input, LSTM, Embedding, Dropout, Activation, Conv1D, GRU, CuDNNGRU, CuDNNLSTM, BatchNormalization
from keras.layers import Bidirectional, GlobalMaxPool1D, MaxPooling1D, Add, Flatten
from keras.layers import GlobalAveragePooling1D, GlobalMaxPooling1D, concatenate, SpatialDropout1D
from keras.models import Model, load_model
from keras import initializers, regularizers, constraints, optimizers, layers, callbacks
from keras import backend as K
from keras.engine import InputSpec, Layer
from keras.optimizers import Adam

from keras.callbacks import ModelCheckpoint, TensorBoard, Callback, EarlyStopping

Using TensorFlow backend.


In [0]:
tk = Tokenizer(lower = True, filters='')
tk.fit_on_texts(full_text)

In [0]:
train_tokenized = tk.texts_to_sequences(train['Phrase'])
test_tokenized = tk.texts_to_sequences(test['Phrase'])

In [0]:
max_len = 50
X_train = pad_sequences(train_tokenized, maxlen = max_len)
X_test = pad_sequences(test_tokenized, maxlen = max_len)

In [0]:
embedding_path = "/content/drive/My Drive/DeepLearning/crawl-300d-2M.vec"
#embedding_path = "/content/drive/My Drive/DeepLearning/glove.twitter.27B.25d.txt"

In [0]:
embed_size = 300
#embed_size = 25
max_features = 30000

In [0]:
def get_coefs(word,*arr): return word, np.asarray(arr, dtype='float32')
embedding_index = dict(get_coefs(*o.strip().split(" ")) for o in open(embedding_path))

word_index = tk.word_index
nb_words = min(max_features, len(word_index))
embedding_matrix = np.zeros((nb_words + 1, embed_size))
for word, i in word_index.items():
    if i >= max_features: continue
    embedding_vector = embedding_index.get(word)
    if embedding_vector is not None: embedding_matrix[i] = embedding_vector

In [0]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse=False)
y_ohe = ohe.fit_transform(y.values.reshape(-1, 1))

An attempt at ensemble:

In [0]:
def build_model(lr=0.0, lr_d=0.0, units=0, spatial_dr=0.0, kernel_size1=3, kernel_size2=2, dense_units=128, dr=0.1, conv_size=32):
    file_path = "/content/drive/My Drive/DeepLearning/best_model.hdf5"
    check_point = ModelCheckpoint(file_path, monitor = "val_loss", verbose = 1,
                                  save_best_only = True, mode = "min")
    early_stop = EarlyStopping(monitor = "val_loss", mode = "min", patience = 4)

    inp = Input(shape = (max_len,))
    x = Embedding(19479, embed_size, weights = [embedding_matrix], trainable = False)(inp)
    x1 = SpatialDropout1D(spatial_dr)(x)

    x_gru = Bidirectional(CuDNNGRU(units, return_sequences = True))(x1)
    x_lstm = Bidirectional(CuDNNLSTM(units, return_sequences = True))(x1)
    
    x_conv1 = Conv1D(conv_size, kernel_size=kernel_size1, padding='valid', kernel_initializer='he_uniform')(x_gru)
    avg_pool1_gru = GlobalAveragePooling1D()(x_conv1)
    max_pool1_gru = GlobalMaxPooling1D()(x_conv1)
    
    x_conv2 = Conv1D(conv_size, kernel_size=kernel_size2, padding='valid', kernel_initializer='he_uniform')(x_gru)
    avg_pool2_gru = GlobalAveragePooling1D()(x_conv2)
    max_pool2_gru = GlobalMaxPooling1D()(x_conv2)
    
    
    x_conv3 = Conv1D(conv_size, kernel_size=kernel_size1, padding='valid', kernel_initializer='he_uniform')(x_lstm)
    avg_pool1_lstm = GlobalAveragePooling1D()(x_conv3)
    max_pool1_lstm = GlobalMaxPooling1D()(x_conv3)
    
    x_conv4 = Conv1D(conv_size, kernel_size=kernel_size2, padding='valid', kernel_initializer='he_uniform')(x_lstm)
    avg_pool2_lstm = GlobalAveragePooling1D()(x_conv4)
    max_pool2_lstm = GlobalMaxPooling1D()(x_conv4)
    
    
    x = concatenate([avg_pool1_gru, max_pool1_gru, avg_pool2_gru, max_pool2_gru,
                    avg_pool1_lstm, max_pool1_lstm, avg_pool2_lstm, max_pool2_lstm])
    x = BatchNormalization()(x)
    x = Dropout(dr)(Dense(dense_units, activation='relu') (x))
    x = BatchNormalization()(x)
    x = Dropout(dr)(Dense(int(dense_units / 2), activation='relu') (x))
    x = Dense(5, activation = "sigmoid")(x)
    model = Model(inputs = inp, outputs = x)
    #model.compile(loss = "binary_crossentropy", optimizer = Adam(lr = lr, decay = lr_d), metrics = ["accuracy"])
    model.compile(loss = "binary_crossentropy", optimizer = 'adamax', metrics = ["accuracy"])
    history = model.fit(X_train, y_ohe, batch_size = 128, epochs = 30, validation_split=0.1, 
                        verbose = 1, callbacks = [check_point, early_stop])
    model = load_model(file_path)
    return model

In [44]:
model1 = build_model(lr = 1e-3, lr_d = 0, units = 64, spatial_dr = 0.5, kernel_size1=3, kernel_size2=3, dense_units=64, dr=0.3, conv_size=32)

Train on 140454 samples, validate on 15606 samples
Epoch 1/30
140454/140454 [==============================] - 75s 533us/step - loss: 0.3801 - acc: 0.8302 - val_loss: 0.3232 - val_acc: 0.8479

Epoch 00001: val_loss improved from inf to 0.32320, saving model to /content/drive/My Drive/DeepLearning/best_model.hdf5
Epoch 2/30
140454/140454 [==============================] - 69s 494us/step - loss: 0.3310 - acc: 0.8513 - val_loss: 0.3149 - val_acc: 0.8512

Epoch 00002: val_loss improved from 0.32320 to 0.31495, saving model to /content/drive/My Drive/DeepLearning/best_model.hdf5
Epoch 3/30
140454/140454 [==============================] - 67s 480us/step - loss: 0.3199 - acc: 0.8548 - val_loss: 0.3110 - val_acc: 0.8557

Epoch 00003: val_loss improved from 0.31495 to 0.31104, saving model to /content/drive/My Drive/DeepLearning/best_model.hdf5
Epoch 4/30
140454/140454 [==============================] - 67s 477us/step - loss: 0.3136 - acc: 0.8570 - val_loss: 0.3083 - val_acc: 0.8577

Epoch 0000

In [1]:
model2 = build_model1(lr = 1e-3, lr_d = 1e-7, units = 64, spatial_dr = 0.3, kernel_size1=3, kernel_size2=3, dense_units=64, dr=0.4, conv_size=64)

NameError: ignored

In [33]:
  file_path = "/content/drive/My Drive/DeepLearning/best_model.hdf5"
  max_len = 50
  embed_size = 300
  max_features = 30000
  lr = 1e-3
  lr_d = 1e-7
  units = 64
  spatial_dr = 0.3
  kernel_size1=3
  kernel_size2=3
  dense_units=64
  dr=0.4
  conv_size=64
  inp = Input(shape = (max_len,))
  x = Embedding(19479, embed_size, weights = [embedding_matrix], trainable = False)(inp)
  x1 = SpatialDropout1D(spatial_dr)(x)

  x_gru = Bidirectional(CuDNNGRU(units, return_sequences = True))(x1)
  x_lstm = Bidirectional(CuDNNLSTM(units, return_sequences = True))(x1)

  x_conv1 = Conv1D(conv_size, kernel_size=kernel_size1, padding='valid', kernel_initializer='he_uniform')(x_gru)
  avg_pool1_gru = GlobalAveragePooling1D()(x_conv1)
  max_pool1_gru = GlobalMaxPooling1D()(x_conv1)

  x_conv2 = Conv1D(conv_size, kernel_size=kernel_size2, padding='valid', kernel_initializer='he_uniform')(x_gru)
  avg_pool2_gru = GlobalAveragePooling1D()(x_conv2)
  max_pool2_gru = GlobalMaxPooling1D()(x_conv2)


  x_conv3 = Conv1D(conv_size, kernel_size=kernel_size1, padding='valid', kernel_initializer='he_uniform')(x_lstm)
  avg_pool1_lstm = GlobalAveragePooling1D()(x_conv3)
  max_pool1_lstm = GlobalMaxPooling1D()(x_conv3)

  x_conv4 = Conv1D(conv_size, kernel_size=kernel_size2, padding='valid', kernel_initializer='he_uniform')(x_lstm)
  avg_pool2_lstm = GlobalAveragePooling1D()(x_conv4)
  max_pool2_lstm = GlobalMaxPooling1D()(x_conv4)


  x = concatenate([avg_pool1_gru, max_pool1_gru, avg_pool2_gru, max_pool2_gru,
                  avg_pool1_lstm, max_pool1_lstm, avg_pool2_lstm, max_pool2_lstm])
  x = BatchNormalization()(x)
  x = Dropout(dr)(Dense(dense_units, activation='relu') (x))
  x = BatchNormalization()(x)
  x = Dropout(dr)(Dense(int(dense_units / 2), activation='relu') (x))
  x = Dense(5, activation = "sigmoid")(x)
  model = Model(inputs = inp, outputs = x)
  model.compile(loss = "binary_crossentropy", optimizer = Adam(lr = lr, decay = lr_d), metrics = ["accuracy"])

  model = load_model(file_path)
  #scores = model.evaluate(x, y, verbose=0)
  #print("%s : %.2f%%" %model.mertics_names[1], scores[1]*100)
  pred1 = model.predict(X_test, batch_size = 1024, verbose = 1)
  print(pred1)

66292/66292 [==============================] - 6s 94us/step
[[1.8538740e-04 1.8561322e-02 2.5829387e-01 6.8309313e-01 5.1312111e-02]
 [2.9846482e-04 2.4059894e-02 2.8592557e-01 6.5972751e-01 4.7395982e-02]
 [6.2336127e-04 3.8427949e-02 8.5681093e-01 9.5356211e-02 8.7779312e-04]
 ...
 [1.0917133e-01 6.9532359e-01 1.7472555e-01 1.5772644e-03 2.2747652e-06]
 [1.0806645e-01 6.8302274e-01 1.8779916e-01 2.2870591e-03 4.3723012e-06]
 [8.3014086e-02 6.8529016e-01 2.1059312e-01 2.8466308e-03 5.0206590e-06]]


In [0]:
pred = pred1

In [37]:
import numpy as np
sub = pd.read_csv('/content/drive/My Drive/DeepLearning/sampleSubmission.csv', sep=",")
predictions = np.round(np.argmax(pred, axis=1)).astype(int)
sub['Sentiment'] = predictions
print(sub['Sentiment'])
sub.to_csv("/content/drive/My Drive/DeepLearning/blend.csv", index=False)

0        3
1        3
2        2
3        3
4        3
5        3
6        3
7        2
8        3
9        2
10       2
11       2
12       2
13       2
14       2
15       3
16       2
17       3
18       3
19       2
20       2
21       2
22       3
23       2
24       2
25       2
26       2
27       2
28       3
29       2
        ..
66262    2
66263    2
66264    2
66265    3
66266    2
66267    2
66268    3
66269    3
66270    2
66271    3
66272    3
66273    2
66274    2
66275    2
66276    2
66277    2
66278    2
66279    2
66280    1
66281    1
66282    1
66283    2
66284    2
66285    2
66286    2
66287    1
66288    1
66289    1
66290    1
66291    1
Name: Sentiment, Length: 66292, dtype: int64
